const fs = require('fs');

// Read the original pristine see-more.html
const seeMore = fs.readFileSync('see-more.html', 'utf8');

const startTag = '<main>';
// Because of how the html structure might be, let's just replace everything inside <main> and </main>
// find the first <main> and the FIRST </main> after it.
const startIndex = seeMore.indexOf('<main>');
const endIndex = seeMore.indexOf('</main>', startIndex);

if (startIndex === -1 || endIndex === -1) {
    console.error('Could not find <main> tags');
    process.exit(1);
}

const htmlBefore = seeMore.substring(0, startIndex + 6); // include <main>
const htmlAfter = seeMore.substring(endIndex); // include </main>

const privacyContent = `
            <section class="fade-in-section info-block" style="padding-top: 40px; padding-bottom: 60px;">
                <h1 style="color: #d4af37; font-family: 'Playfair Display', serif; font-size: 2.5rem; margin-bottom: 10px;">Privacy <em>Policy</em></h1>
                <p style="color: rgba(255, 255, 255, 0.5); font-size: 0.9rem; margin-bottom: 40px;">Last Updated: August 2026</p>

                <div style="color: rgba(255, 255, 255, 0.8); line-height: 1.8; font-family: 'Space Grotesk', sans-serif;">
                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">1. Introduction</h2>
                    <p style="margin-bottom: 20px;">Welcome to Crestiva Web Studio. We respect your privacy and are committed to protecting your personal information. This Privacy Policy explains how personal information may be collected, used, stored, and shared when you interact with our website or use our services.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">2. Information We May Collect</h2>
                    <p style="margin-bottom: 10px;">We may collect information that you voluntarily provide to us when you express an interest in our services. This may include:</p>
                    <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                        <li><strong>Contact Information:</strong> Name, email address, phone number, and business/company name.</li>
                        <li><strong>Project Details:</strong> Information, project requirements, or messages voluntarily submitted through our contact forms.</li>
                        <li><strong>Payment-Related Information:</strong> Information necessary to process a transaction when initiating a project.</li>
                    </ul>
                    <p style="margin-bottom: 20px;">We clearly distinguish the information you voluntarily provide from technical information automatically generated by your interaction with the website.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">3. Contact Forms</h2>
                    <p style="margin-bottom: 10px;">Our website utilizes Supabase to manage contact form submissions. Information submitted through these forms may include your name, email, phone, business name, and message/project requirements. We collect this information strictly for:</p>
                    <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                        <li>Responding to inquiries.</li>
                        <li>Understanding your project requirements.</li>
                        <li>Communicating with prospective clients.</li>
                        <li>Providing the requested web design and development services.</li>
                    </ul>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">4. Payment Information</h2>
                    <p style="margin-bottom: 10px;">Crestiva Web Studio requires a 25% advance payment when a customer purchases a website plan or service, according to the applicable plan or agreement. We intend to use Razorpay as our secure third-party payment processor.</p>
                    <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                        <li><strong>Current Implementation:</strong> The Razorpay integration on our current website is operating in TEST MODE for development and testing purposes. Live customer payment processing is not yet enabled.</li>
                        <li><strong>Production Intention:</strong> Live Razorpay payment processing will be enabled only after our production backend is fully implemented and configured. Once live payments are enabled, processing will be handled entirely through Razorpay's secure payment infrastructure.</li>
                    </ul>
                    <p style="margin-bottom: 20px;">We do not store sensitive payment credentials such as complete credit/debit card numbers, CVV numbers, banking passwords, or UPI PINs on our servers.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">5. Third-Party Services</h2>
                    <p style="margin-bottom: 10px;">We utilize specific third-party services necessary for our core functionality. These include:</p>
                    <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                        <li><strong>Supabase:</strong> Used for database management and secure contact form processing.</li>
                        <li><strong>Razorpay:</strong> Intended for processing customer payments (currently in test mode).</li>
                        <li><strong>WhatsApp & Email:</strong> Used for direct client communication and project support via integrated links.</li>
                    </ul>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">6. Local Storage & Session Data</h2>
                    <p style="margin-bottom: 20px;">Our website utilizes standard browser capabilities, such as <code>localStorage</code>, to temporarily save authentication state, user emails (for session tracking), and Custom Builder choices locally on your device. This ensures a seamless browsing experience. <code>localStorage</code> is not a remote database and does not store highly sensitive information beyond what is necessary to maintain your session state locally.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">7. Data Use</h2>
                    <p style="margin-bottom: 10px;">We use the information collected for legitimate business purposes, including:</p>
                    <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                        <li>Responding to inquiries and communicating with users.</li>
                        <li>Understanding project requirements and providing web development services.</li>
                        <li>Processing payments through applicable payment providers.</li>
                        <li>Maintaining and improving the website.</li>
                        <li>Preventing abuse or unauthorized activity.</li>
                    </ul>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">8. Data Sharing</h2>
                    <p style="margin-bottom: 20px;">We do not sell personal information. Information may be shared with necessary third-party service providers only when required to provide the relevant functionality or service (for example, with Supabase for form functionality, or with Razorpay for payment processing once live payments are enabled).</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">9. Data Security</h2>
                    <p style="margin-bottom: 20px;">We implement reasonable technical and organizational security measures designed to protect the personal information we process. However, please remember that no method of transmission over the internet or electronic storage system can be guaranteed to be completely secure.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">10. Data Retention</h2>
                    <p style="margin-bottom: 20px;">We retain your information only for as long as reasonably necessary for the purposes for which it was collected, to fulfill legal obligations, resolve disputes, or support legitimate business requirements, where applicable.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">11. User Rights</h2>
                    <p style="margin-bottom: 20px;">Subject to applicable legal requirements, you may contact us to request information about your personal data or ask for correction or deletion of the information we have collected about you.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">12. Children</h2>
                    <p style="margin-bottom: 20px;">Our website and services are not intentionally directed toward children. Users should not submit personal information if they are not legally permitted to do so.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">13. Policy Updates</h2>
                    <p style="margin-bottom: 20px;">We may update this Privacy Policy from time to time when our website, services, technology, or applicable legal requirements change. We encourage you to review this policy periodically.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">14. Contact Information</h2>
                    <p style="margin-bottom: 20px;">If you have any questions or comments about this Privacy Policy or our practices, please email us at: <strong>crestivawebstudio@gmail.com</strong>.</p>
                </div>
            </section>
`;

const termsContent = `
            <section class="fade-in-section info-block" style="padding-top: 40px; padding-bottom: 60px;">
                <h1 style="color: #d4af37; font-family: 'Playfair Display', serif; font-size: 2.5rem; margin-bottom: 10px;">Terms of <em>Service</em></h1>
                <p style="color: rgba(255, 255, 255, 0.5); font-size: 0.9rem; margin-bottom: 40px;">Last Updated: August 2026</p>

                <div style="color: rgba(255, 255, 255, 0.8); line-height: 1.8; font-family: 'Space Grotesk', sans-serif;">
                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">1. Acceptance of Terms</h2>
                    <p style="margin-bottom: 20px;">By accessing and using the website and services of Crestiva Web Studio, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you are prohibited from using or accessing this site or our services.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">2. Services Provided</h2>
                    <p style="margin-bottom: 20px;">Crestiva Web Studio provides custom web design, web development, performance optimization, and related digital services. The specific scope, deliverables, and timeline for each project will be agreed upon mutually prior to the commencement of work.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">3. Project Initiation and Payment</h2>
                    <p style="margin-bottom: 10px;">To initiate a project, an advance payment (typically 25% to 50%, depending on the agreement) is required. This secures your spot in our development schedule.</p>
                    <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                        <li>All payments are processed securely via our authorized payment gateway (Razorpay).</li>
                        <li>Final deliverables and source code access are provided only after full payment of the project invoice has been received.</li>
                    </ul>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">4. Client Responsibilities</h2>
                    <p style="margin-bottom: 20px;">The client agrees to provide all necessary materials, content, brand assets, and timely feedback required for the successful completion of the project. Delays in providing necessary information may result in adjustments to the agreed timeline.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">5. Intellectual Property</h2>
                    <p style="margin-bottom: 20px;">Upon completion of the project and receipt of full payment, the client assumes ownership of the final website design and content. Crestiva Web Studio retains the right to display the completed project in our portfolio and marketing materials as examples of our work.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">6. Third-Party Integrations</h2>
                    <p style="margin-bottom: 20px;">Our websites may integrate with third-party tools, APIs, or hosting services. We are not responsible for any issues, downtime, or policy changes originating from these third-party providers once the site is handed over.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">7. Limitation of Liability</h2>
                    <p style="margin-bottom: 20px;">In no event shall Crestiva Web Studio or its founders be liable for any indirect, consequential, incidental, or punitive damages, including loss of profits or data, arising out of your use of our services or website.</p>

                    <h2 style="color: #f0f0f0; font-family: 'Playfair Display', serif; font-size: 1.5rem; margin-top: 40px; margin-bottom: 15px;">8. Contact Information</h2>
                    <p style="margin-bottom: 20px;">If you have any questions regarding these Terms, please contact us at: <strong>crestivawebstudio@gmail.com</strong>.</p>
                </div>
            </section>
`;

let privacyHtml = htmlBefore + '\n' + privacyContent + '\n' + htmlAfter;
let termsHtml = htmlBefore + '\n' + termsContent + '\n' + htmlAfter;

// CLEAN UP SEO FOR PRIVACY
privacyHtml = privacyHtml.replace(/<link rel="canonical" href=".*?" \/>/g, '');
privacyHtml = privacyHtml.replace(/(<meta name="description" content=".*?" \/>)/, '$1\n    <link rel="canonical" href="https://crestivawebstudio.online/privacy-policy" />');
privacyHtml = privacyHtml.replace(/<title>.*?<\/title>/g, '<title>Privacy Policy | Crestiva Web Studio</title>');
privacyHtml = privacyHtml.replace(/<meta property="og:title" content=".*?" \/>/g, '<meta property="og:title" content="Privacy Policy | Crestiva Web Studio" />');
privacyHtml = privacyHtml.replace(/<meta property="og:description" content=".*?" \/>/g, '<meta property="og:description" content="Privacy Policy for Crestiva Web Studio." />');
privacyHtml = privacyHtml.replace(/<meta property="og:url" content=".*?" \/>/g, '<meta property="og:url" content="https://crestivawebstudio.online/privacy-policy" />');
privacyHtml = privacyHtml.replace(/<meta name="twitter:title" content=".*?" \/>/g, '<meta name="twitter:title" content="Privacy Policy | Crestiva Web Studio" />');
privacyHtml = privacyHtml.replace(/<meta name="twitter:description" content=".*?" \/>/g, '<meta name="twitter:description" content="Privacy Policy for Crestiva Web Studio." />');


// CLEAN UP SEO FOR TERMS
termsHtml = termsHtml.replace(/<link rel="canonical" href=".*?" \/>/g, '');
termsHtml = termsHtml.replace(/(<meta name="description" content=".*?" \/>)/, '$1\n    <link rel="canonical" href="https://crestivawebstudio.online/terms" />');
termsHtml = termsHtml.replace(/<title>.*?<\/title>/g, '<title>Terms of Service | Crestiva Web Studio</title>');
termsHtml = termsHtml.replace(/<meta property="og:title" content=".*?" \/>/g, '<meta property="og:title" content="Terms of Service | Crestiva Web Studio" />');
termsHtml = termsHtml.replace(/<meta property="og:description" content=".*?" \/>/g, '<meta property="og:description" content="Terms of Service for Crestiva Web Studio." />');
termsHtml = termsHtml.replace(/<meta property="og:url" content=".*?" \/>/g, '<meta property="og:url" content="https://crestivawebstudio.online/terms" />');
termsHtml = termsHtml.replace(/<meta name="twitter:title" content=".*?" \/>/g, '<meta name="twitter:title" content="Terms of Service | Crestiva Web Studio" />');
termsHtml = termsHtml.replace(/<meta name="twitter:description" content=".*?" \/>/g, '<meta name="twitter:description" content="Terms of Service for Crestiva Web Studio." />');


fs.writeFileSync('privacy-policy.html', privacyHtml);
fs.writeFileSync('terms.html', termsHtml);
console.log('Cleaned and generated pages.');
